- name: Manage Entries in sysfs.conf
  lineinfile:
    dest: "{{ sysfs_config_file }}"
    state: present
    line: "{{ item.param }} = {{ item.value }}"
    regexp: "^{{ item.param | regex_escape() }}"
  with_items: "{{ sysfs_config }}"
